QuestionUpdates:
    type: entity
    table: question_updates
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
