Questions:
    type: entity
    table: questions
    id:
        questionId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: question_id
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        ownerName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: owner_name
        score:
            type: integer
            nullable: false
            options:
                unsigned: false
        creationDate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: creation_date
        link:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        isAnswered:
            type: boolean
            nullable: false
            column: is_answered
        created:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
